<?php
    function clock_angle_menu(){
        $items['clock_angle'] = array(
            'title' => 'Clock Angle',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('clock_angle_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        return $items;
    }
    function clock_angle_form(){
        $form['hours'] = array(
            '#title' => 'Hour Hand',
            '#type' => 'textfield',
            '#description' => t('Enter value representing the hour hand'),
        );
        $form['minutes'] = array(
            '#title' => 'Minute Hand',
            '#type' => 'textfield',
            '#description' => t('Enter a value representing a minute hand'),
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Check Clock Angle',
        );
        return $form;
    }
